### PR TITLE
Update to Nancy version 2.0.0-pre1903

### PR DESCRIPTION
**Pull request by vik-borisov**
### Prerequisites

- [x] I have written a descriptive pull-request title
- [x] I have verified that there are no overlapping [pull-requests](https://github.com/NancyFx/Nancy.Bootstrappers.Windsor/pulls) open
- [x] I have verified that I am following the Nancy [code style guidelines](https://github.com/NancyFx/Nancy/blob/45238076ad0b7f6ecabd6bae8469e30458d02efe/CONTRIBUTING.md#style-guidelines)
- [x] I have provided test coverage for my change (where applicable)

### Description
- apply code style
- remove direct reference to nancy
- add Nancy with version 2.0.0-pre1903

### CODE REVIEW

**Comment by vik-borisov** [comment]
You will also need to modify the build script - run the build.ps1 script (also as build Nancy)

**Comment by vik-borisov** [comment]
@khellang
can you look at this PR?
Myget does not have this package. Can you combine this PR, change CI and build this package?

**Comment by thecodejunkie** [comment]
@vik-borisov Hi. No the solution is not to pull this pull-request. The problem is elsewhere and that's what we need to identify and solve

**Comment by vik-borisov** [comment]
@thecodejunkie
Have you watched my PR?
1) I migrated the Nancy package library instead of a direct link
2) I fixed the build scripts

these are the same problems as this PR in Nancy https://github.com/NancyFx/Nancy/pull/2861

this package is missing from nancy myget feed now.

why do you think that this will not solve the problem?

**Comment by thecodejunkie** [comment]
hmm sorry github was showing me another view that related it to one of your other PRs.. =/ will have a look later

**Comment by vik-borisov** [comment]
@damianh, @thecodejunkie  ping!

**Pull request closed without merging**
